name: test

on:
  push:
    paths:
      - '**.py'
      - ".github/workflows/*.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'
      - ".github/workflows/*.yml"
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          # Set this option if you want the action to check for the latest available version that satisfies the version spec.
          # check-latest: # optional
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          sudo apt update && sudo apt install graphviz
      - name: Cache wabt
        id: cache-wabt
        uses: actions/cache@v4
        with:
          path: wabt-1.0.32
          key: wabt
      - name: Install wabt
        if: steps.cache-wabt.outputs.cache-hit != 'true'
        run: |
          curl -JLO "https://github.com/WebAssembly/wabt/releases/download/1.0.32/wabt-1.0.32-ubuntu.tar.gz"
          tar xzf wabt-1.0.32-ubuntu.tar.gz
      - name: Run pytest
        run: |
          export PATH=$(pwd)/wabt-1.0.32/bin:$PATH
          pytest test/test.py --tb=short --durations=0